version: '3.8'

services:
  warehouse-service:
    build: .
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://warehouse_user:warehouse_password@warehouse-db:5432/warehouse_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_EXCHANGE=cargo_track_events
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - LOG_LEVEL=INFO
      - APP_NAME=Warehouse Service
      - DEBUG=true
      - DOCKER_ENV=true
    depends_on:
      - warehouse-db
    volumes:
      - .:/app
      - ../shared:/app/src/shared
    networks:
      - cargo-track-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  warehouse-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=warehouse_db
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_password
    ports:
      - "5434:5432"
    volumes:
      - warehouse_postgres_data:/var/lib/postgresql/data
    networks:
      - cargo-track-network

volumes:
  warehouse_postgres_data:

networks:
  cargo-track-network:
    external: true 