version: '3.8'

services:
  orders-service:
    build: .
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@orders-db:5432/orders_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_EXCHANGE=cargo_track_events
      - SECRET_KEY=your-secret-key-here
      - LOG_LEVEL=INFO
    depends_on:
      - orders-db
      - rabbitmq
    volumes:
      - ./src:/app/src
      - ../shared:/app/src/shared
    networks:
      - orders-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  orders-db:
    image: postgres:13
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data
    networks:
      - orders-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - orders-network

volumes:
  orders_postgres_data:
  rabbitmq_data:

networks:
  orders-network:
    driver: bridge 