version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth_db
      - SECRET_KEY=your-secret-key-here
      - LOG_LEVEL=INFO
    depends_on:
      - auth-db
    volumes:
      - .:/app
      - ../shared:/app/shared
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  auth-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data: 