version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://auth_user:auth_password@auth-db:5432/auth_db
      - SECRET_KEY=your-secret-key-here
      - LOG_LEVEL=INFO
    depends_on:
      - auth-db
    volumes:
      - .:/app
      - ../shared:/app/shared
    networks:
      - auth-network

  auth-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

volumes:
  auth_postgres_data:

networks:
  auth-network:
    driver: bridge 